name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        python3 -m unittest
  test_dependency:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run import packages tests
      run: |
        pip3 install -r requirements.txt 
        python3 env.py
